drop table if exists event CASCADE;
    create table event
    (
        id   bigint generated by default as identity,
        event_name varchar(255),
        start_date Date,

        primary key (id)
    );

insert into event values(1,	'인공지능', '2022-04-06'),
(2,	'임베디드', '2022-04-07'),
(3,	'시스템보안', '2022-04-08'),
(4,	'데이터베이스', '2022-04-09'),
(5,	'영상처리', '2022-04-10')

insert into member values(1, '가가'),
(2, '나나'),
(3, '다다'),
(4, '라라'),
(5, '마마')

insert into tag values(1,	'인공지능'),
(2,	'임베디드'),
(3,	'시스템보안'),
(4,	'데이터베이스'),
(5,	'영상처리')

