drop table if exists member CASCADE;
    create table member
    (
        id   bigint generated by default as identity,
        name varchar(255),

        primary key (id)
    );

insert into member values(1,	'나나'),
(2,	'도도'),
(3,	'라라'),
(4,	'무무')
